language: python

sudo: required

services:
- docker

python:
- 2.7
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly
- pypy-5.3.1

before_install:
- docker build -t boutiques/example1:test ./tools/python/boutiques/schema/examples/example1

install:
- pip install coveralls pytest pytest-runner
- pip install ./tools/python/

script:
- cd ./tools/python/
- coverage run --source boutiques setup.py pytest

after_success:
- coveralls

deploy:
