language: python

python:
- 2.7
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly
- pypy-5.3.1

install:
- pip install nose
- pip install coveralls
- pip install ./tools/python/

script:
- cd ./tools/python/
- coverage run --source boutiques setup.py test

after_success:
- coveralls

deploy:
